# Generated by Django 5.1.4 on 2025-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdataupload',
            name='headers',
            field=models.JSONField(blank=True, help_text='Column headers from the uploaded file', null=True),
        ),
        migrations.AddField(
            model_name='billingdataupload',
            name='sample_data',
            field=models.JSONField(blank=True, help_text='Sample data rows from the uploaded file', null=True),
        ),
    ]
