# Generated by Django 5.1.4 on 2025-05-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_billingdataupload_headers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdataupload',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='billingdataupload',
            name='sample_data',
        ),
    ]
