# Generated by Django 5.1.4 on 2025-05-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_billingdataupload_headers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdataupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('mapped', 'Mapped'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', help_text='Current processing status of the upload', max_length=20),
        ),
    ]
