# Generated by Django 4.2.11 on 2025-01-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_transaction_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
