# Generated by Django 5.1.4 on 2025-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='free_trial_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of days for free trial period (if enabled)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_free_trial',
            field=models.BooleanField(default=False, help_text='Whether this plan offers a free trial'),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_yearly_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly price in dollars. If not set, will default to monthly price × 12', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.0', help_text='Monthly price in dollars', max_digits=9),
        ),
    ]
