# Generated by Django 5.1.4 on 2025-05-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_plan_free_trial_days_plan_has_free_trial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subscription_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'cancelled'), (3, 'past due'), (4, 'ended')], default=0),
        ),
    ]
